// <auto-generated />
using API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
[DbContext(typeof(UCContext))]
[Migration("20240228234621_ranks")]
partial class Ranks
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.2").HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Shared.Entities.LinkEntity",
                            b =>
                            {
                                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName(
                                    "id");

                                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                                b.Property<string>("Url")
                                    .IsRequired()
                                    .HasMaxLength(2048)
                                    .HasColumnType("character varying(2048)")
                                    .HasColumnName("url");

                                b.HasKey("Id");

                                b.ToTable("link");
                            });

        modelBuilder.Entity("Shared.Entities.RankEntity",
                            b =>
                            {
                                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName(
                                    "id");

                                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                                b.Property<long>("Conversions").HasColumnType("bigint").HasColumnName("conversions");

                                b.Property<string>("Converter")
                                    .IsRequired()
                                    .HasMaxLength(18)
                                    .HasColumnType("character varying(18)")
                                    .HasColumnName("converter");

                                b.HasKey("Id");

                                b.ToTable("rank");
                            });
#pragma warning restore 612, 618
    }
}
}
